from .address_conftest import *
from .admission_conftest import *
from .attendance_room_conftest import *
from .bed_conftest import *
from .clinical_evolution_history_conftest import *
from .company_address_conftest import *
from .contact_conftest import *
from .contract_rule_conftest import *
from .cooperative_conftest import *
from .death_launch_conftest import *
from .diagnosis_conftest import *
from .enablement_conftest import *
from .equipment_conftest import *
from .fces import *
from .institution_conftest import *
from .item_classification_conftest import *
from .maintainer_conftest import *
from .medical_appointment_conftest import *
from .medical_prescription_conftest import *
from .medical_specialty_conftest import *
from .medicine_conftest import *
from .patient_conftest import *
from .pharmacy import *
from .physical_installation_conftest import *
from .prescription_conftest import *
from .professional_conftest import *
from .protocol_conftest import *
from .question_conftest import *
from .regional_council_conftest import *
from .risk_classification_conftest import *
from .room_conftest import *
from .sae_conftest import *
from .sanitary_district_conftest import *
from .service_classification_conftest import *
from .unit_measurement_conftest import *
from .user_conftest import *
from .vaccine_application_conftest import *
from .vaccine_application_maintenance_conftest import *
from .vaccine_application_request_conftest import *
from .vaccine_conftest import *
from .vital_signs_control_conftest import *
