BOND_OPTIONS = ["CLT", "CESSÃO", "PL", "RESIDÊNCIA", "ESTÁGIO"]

DISMISSAL_CAUSE_OPTIONS = [
    "ABANDONO DE EMPREGO",
    "APOSENTADORIA",
    "DEMISSÃO",
    "ESTABELECIMENTO DESATIVADO",
    "LICENÇA/AFASTAMENTO PELO PERÍODO SUPERIOR A 60 DIAS",
    "MORTE",
    "TÉRMINO DE CONTRATO",
    "TRANSF. PARA OUTRO ESTABELECIMENTO DE OUTRO MUNICÍPIO/ESTADO",
    "TRANSF. PARA OUTRO ESTABELECIMENTO DO MESMO MUNICÍPIO",
]
