from .action_controller import *
from .activation_controller import *
from .admission_controller import *
from .attendance_room_controller import *
from .auth_controller import *
from .bed import *
from .cid_10_controller import *
from .clinical_evolution_controller import *
from .contract_rule_controller import *
from .cooperative_controller import *
from .death_launch_controller import *
from .diagnosis_controller import *
from .discharge_conditions_controller import *
from .enablement_controller import *
from .equipment import *
from .fces import *
from .history_controller import *
from .institution import *
from .item_classification_controller import *
from .maintainer_controller import *
from .medical_appointment_controller import *
from .medical_prescription_controller import *
from .medical_specialty_controller import *
from .medicine_controller import *
from .password_controller import *
from .patient_controller import *
from .pharmacy import *
from .physical_installation import *
from .prescription_controller import *
from .procedure_controller import *
from .professional_bond_controller import *
from .professional_controller import *
from .protocol_controller import *
from .question_controller import *
from .queue_controller import *
from .queue_manager_controller import *
from .regional_council_controler import *
from .role_controller import *
from .resource_controller import *
from .risk_classification_controller import *
from .role_controller import *
from .room_controller import *
from .sae_controller import *
from .sanitary_district_controller import *
from .service_classification import *
from .unit_measurement_controller import *
from .user_controller import *
from .vaccine import *
from .vaccine_application import *
