from .base_medical_appointment import *
from .base_seed_action import *
from .base_seed_admission import *
from .base_seed_admission_action_association import *
from .base_seed_admission_question_association import *
from .base_seed_attendance_room import *
from .base_seed_call_panel import *
from .base_seed_cid_10 import *
from .base_seed_clinical_evolution import *
from .base_seed_contract_rule import *
from .base_seed_cooperative import *
from .base_seed_death_launch import *
from .base_seed_diagnosis import *
from .base_seed_discharge_conditions import *
from .base_seed_enablement import *
from .base_seed_item_classification import *
from .base_seed_maintainer import *
from .base_seed_medical_prescription import *
from .base_seed_medical_specialty import *
from .base_seed_medicine import *
from .base_seed_patient import *
from .base_seed_prescription import *
from .base_seed_procedure import *
from .base_seed_professional import *
from .base_seed_protocol import *
from .base_seed_question import *
from .base_seed_queue_manager import *
from .base_seed_regional_council import *
from .base_seed_risk_classification import *
from .base_seed_roles import *
from .base_seed_room import *
from .base_seed_sae_perform import *
from .base_seed_sanitary_district import *
from .base_seed_unit_measurement import *
from .base_seed_user import *
from .base_seed_vaccine_application import *
from .base_seed_vaccine_application_request import *
from .base_seed_vital_signs_control import *
from .bed import *
from .equipment import *
from .fces import *
from .institution import *
from .pharmacy import *
from .physical_installation import *
from .service_classification import *
from .vaccine import *
